### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by nogElBoss** [nogElBoss/secondTest#1]
### Task List
- [x] Create layout;
- [x] Create issue to create NextJS app with [ChakraUI](https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui);
- [x] Brake layout into components (Create issue for each component);
- [x] Create an issue for each page;
- [x] Create issue to deploy the app to Vercel;
- [x] Create issue to run lighthouse after finishing each page;
- [ ] Create PR for each component on specific branch;
- [ ] All the issues should be tagged on the commit;
